version: '3'

services:
  ZhaoPinGou:
    image: zhao-pin-gou
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  default:
    external:
      name: nginx-net